### ISSUE TITLE
Improvement: Visual elements in the administration page

### ISSUE THREAD

**Issue by stdoma** [srobotta/moodle-tiny_htmlblock#6]
Hello!
I have a small visual idea for the administration page.
If you define several entries and the list gets longer, you might get a little lost in the input fields.

I have stored a few CSS definitions in the SCSS of the theme:
![Screenshot 2024-03-14 105751](https://github.com/srobotta/moodle-tiny_htmlblock/assets/92015860/dad35998-4982-4ff1-95e9-4682808519de)

CSS:
[tiny_htmlblock_RawSCSS.txt](https://github.com/srobotta/moodle-tiny_htmlblock/files/14600352/tiny_htmlblock_RawSCSS.txt)

Maybe other people feel like me when they see lots of elements on a white background ;)

**Comment by srobotta** [comment]
This has been fixed with version 1.4
